plotting_python: /mnt/home/wysongj2/.conda/envs/mhd/bin/python
gnuplot: /mnt/home/wysongj2/.conda/envs/mhd/bin/gnuplot
athenapk: /mnt/home/wysongj2/athenapk/build-host/bin/athenaPK
# cannot currently use mpi if want .pdhf's
# h5py not compatible. But good for convergence test runs
athenapk_mpi: /mnt/home/wysongj2/athenapk/build-mpi/bin/athenaPK

results_root: /mnt/home/wysongj2/athenapk/test-suite-uct-ct-glm
report_description: report/workflow.rst

dimension: 2D

fluids:
  - ctmhd
  - ucthlldmhd
  - glmmhd

reconstruction: plm
riemann: hlld
integrator: rk2




tests:
  smooth_vortex:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/smooth_mhd_vortex.in
    dirname: smooth_mhd_vortex
    order_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/compute_smooth_vortex_orders.py
    resolutions: [16, 32, 64, 128, 256]

  linear_wave:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/linear_mhd_wave.in
    dirname: linear_mhd_wave_unrefined
    order_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/linear_mhd_wave_orders.py
    waves: [0, 1, 2, 4, 5, 6]
    resolutions: [16, 32, 64, 128]

    mesh:
      2D:
        ang_2: 0.0

      
      3D:

  linear_wave_static:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/linear_mhd_wave.in
    dirname: linear_mhd_wave_static
    order_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/linear_mhd_wave_orders.py
    waves: [0, 1, 2, 4, 5, 6]
    resolutions: [16, 32, 64, 128]
    mesh_plot_resolution: 16

    refinement_regions:
      - x1min: 0.5
        x1max: 2.5
        x2min: 0.25
        x2max: 1.25
        x3min: 0.25
        x3max: 1.25
        level: 1

      - x1min: 1.0
        x1max: 2.0
        x2min: 0.5
        x2max: 1.0
        x3min: 0.5
        x3max: 1.0
        level: 2

      # - x1min: 1.25
      #   x1max: 1.75
      #   x2min: 0.65
      #   x2max: 0.85
      #   x3min: 0.65
      #   x3max: 0.85
      #   level: 3

  cpaw:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/cpaw.in
    dirname: cpaw
    order_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/cpaw_orders.py
    resolutions: [16, 32, 64, 128]

    mesh:
      2D:
        ang_2: 0.0

      
      3D:


  cpaw_static:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/cpaw.in
    dirname: cpaw_static
    order_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/cpaw_orders.py
    resolutions: [16, 32, 64, 128]
    mesh_plot_resolution: 16

    refinement_regions:
      - x1min: 0.5
        x1max: 2.5
        x2min: 0.25
        x2max: 1.25
        x3min: 0.25
        x3max: 1.25
        level: 1

      - x1min: 1.0
        x1max: 2.0
        x2min: 0.5
        x2max: 1.0
        x3min: 0.5
        x3max: 1.0
        level: 2


  cpaw_viz:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/cpaw.in
    dirname: cpaw_viz
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/cpaw_viz.py
    dimension: 2D
    fluid: ctmhd
    resolution: 64
    output_dt: 0.01

    mesh:
      ang_2: 0.0

    scenarios:
      traveling:
        v_par: 1.0
        dir: 1
      standing:
        v_par: 1.0
        dir: 2



  field_loop:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/field_loop.in
    dirname: field_loop
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/field_loop_video.py
  
    paraview_movie:
        enabled: false
        source: /mnt/home/wysongj2/athenapk/field_loop_3D_movie.mp4
        fluids: [ctmhd]

    mesh:
      2D:
        nx1: 128
        nx2: 64
        nx3: 1
        mb_nx1: 128
        mb_nx2: 64
        mb_nx3: 1
        iprob: 1
      
      3D:
        nx1: 128
        nx2: 64
        nx3: 64
        mb_nx1: 128
        mb_nx2: 64
        mb_nx3: 64
        iprob: 4

  field_loop_orientations:
    enabled: true
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/field_loop.in
    dirname: field_loop_orientations
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/field_loop_video.py

    mesh:
      2D:
        nx1: 64
        nx2: 32
        nx3: 1
        mb_nx1: 64
        mb_nx2: 32
        mb_nx3: 1
        iprob: 1

    orientations:
      right:
        vflow1: 1.0
        vflow2: 0.0
      left:
        vflow1: -1.0
        vflow2: 0.0
      up:
        vflow1: 0.0
        vflow2: 1.0
      down:
        vflow1: 0.0
        vflow2: -1.0
      up-right:
        vflow1: 1.0
        vflow2: 1.0
      up-left:
        vflow1: -1.0
        vflow2: 1.0
      down-right:
        vflow1: 1.0
        vflow2: -1.0
      down-left:
        vflow1: -1.0
        vflow2: -1.0

  field_loop_refined:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/field_loop.in
    dirname: field_loop_refined
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/field_loop_AMR.py

    mesh:
      2D:
        nx1: 128
        nx2: 64
        nx3: 1
        mb_nx1: 32
        mb_nx2: 16
        mb_nx3: 1
        iprob: 1
      
      3D:
        nx1: 64
        nx2: 32
        nx3: 32
        mb_nx1: 16
        mb_nx2: 8
        mb_nx3: 8
        iprob: 4

  field_loop_static_refined:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/field_loop.in
    dirname: field_loop_static_refined
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/field_loop_AMR.py
    problem_id: field_loop_static_centered

    mesh:
      nx1: 128
      nx2: 64
      nx3: 64
      mb_nx1: 32
      mb_nx2: 16
      mb_nx3: 16
      iprob: 4

    refinement_regions:
      - x1min: -0.5
        x1max: 0.5
        x2min: -0.25
        x2max: 0.25
        x3min: -0.25
        x3max: 0.25
        level: 1

  orszag_tang:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/orszag_tang.in
    dirname: orszag_tang
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/orszag_tang_video.py
    resolution: [256, 256]

  orszag_tang_refined:
    enabled: false
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/orszag_tang.in
    dirname: orszag_tang_refined
    movie_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/orszang_tang_AMR.py
    resolution: [256, 256]

  orszag_tang_static:
    enabled: false
    fluids:
      - ctmhd
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/orszag_tang.in
    dirname: orszag_tang_static
    movie_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/orszang_tang_AMR.py
    resolution: [256, 256]
    meshblock: [64, 64]
    output_dt: 0.01
    history_dt: 0.005

    refinement_regions:
      - x1min: 0.0
        x1max: 1.0
        x2min: 0.0
        x2max: 0.25
        level: 1

      - x1min: 0.0
        x1max: 1.0
        x2min: 0.75
        x2max: 1.0
        level: 1

      - x1min: 0.25
        x1max: 0.75
        x2min: 0.0
        x2max: 0.125
        level: 2

      - x1min: 0.25
        x1max: 0.75
        x2min: 0.875
        x2max: 1.0
        level: 2

  current_sheet:
    enabled: false
    fluids:
      - ctmhd
      - ucthlldmhd
    input: /mnt/home/wysongj2/athenapk/inputs/ct_glm_compatible/current_sheet.in
    dirname: current_sheet
    plotting_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/current_sheet_movie.py
    field_line_script: /mnt/home/wysongj2/athenapk/workflow/diagnostics_scripts/current_sheet_field_lines.py
    resolution: [256, 256]
