import os


configfile: "workflow/config.yaml"


def expand_config_environment(value):
    """Expand $HOME and other environment variables in every configured path."""
    if isinstance(value, dict):
        return {key: expand_config_environment(item) for key, item in value.items()}
    if isinstance(value, list):
        return [expand_config_environment(item) for item in value]
    if isinstance(value, str):
        return os.path.expanduser(os.path.expandvars(value))
    return value


config.update(expand_config_environment(config))
report: config.get("report_description", "report/workflow.rst")

include: "rules/smooth_vortex.smk"
include: "rules/linear_wave.smk"
include: "rules/linear_wave_static.smk"
include: "rules/field_loop.smk"
include: "rules/field_loop_orientations.smk"
include: "rules/field_loop_refined.smk"
include: "rules/field_loop_static_refined.smk"
include: "rules/orszag_tang.smk"
include: "rules/orszag_tang_refined.smk"
include: "rules/orszag_tang_static.smk"
include: "rules/current_sheet.smk"
include: "rules/cpaw.smk"
include: "rules/cpaw_static.smk"
include: "rules/cpaw_viz.smk"
include: "rules/resistive_ct_analytic.smk"





rule all:
    input:
        smooth_vortex_targets,
        linear_wave_targets,
        linear_wave_static_targets,
        field_loop_targets,
        field_loop_orientation_targets,
        field_loop_refined_targets,
        field_loop_static_refined_targets,
        orszag_tang_targets,
        orszag_tang_refined_targets,
        orszag_tang_static_targets,
        current_sheet_targets,
        cpaw_targets,
        cpaw_static_targets,
        cpaw_viz_targets,
        resistive_ct_analytic_targets
