configfile: "workflow/config.yaml"
report: config.get("report_description", "report/workflow.rst")

include: "rules/smooth_vortex.smk"
include: "rules/linear_wave.smk"
include: "rules/linear_wave_static.smk"
include: "rules/field_loop.smk"
include: "rules/field_loop_orientations.smk"
include: "rules/field_loop_refined.smk"
include: "rules/field_loop_static_refined.smk"
include: "rules/orszag_tang.smk"
include: "rules/orszag_tang_refined.smk"
include: "rules/orszag_tang_static.smk"
include: "rules/current_sheet.smk"
include: "rules/cpaw.smk"
include: "rules/cpaw_static.smk"
include: "rules/cpaw_viz.smk"





rule all:
    input:
        smooth_vortex_targets,
        linear_wave_targets,
        linear_wave_static_targets,
        field_loop_targets,
        field_loop_orientation_targets,
        field_loop_refined_targets,
        field_loop_static_refined_targets,
        orszag_tang_targets,
        orszag_tang_refined_targets,
        orszag_tang_static_targets,
        current_sheet_targets,
        cpaw_targets,
        cpaw_static_targets,
        cpaw_viz_targets
